/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f070xb.h"
#include "i2c.h"

int main(void) {

	gpio_led_init();
	gpio_button_init();
	gpio_i2c2_init_master();
	gpio_i2c1_init_slave();
	i2c2_init();
	i2c1_init();
	exti_init();
	/* Main loop */
    while(1) {
    }

    return 0;
}

