/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f070xb.h"
#include "i2c.h"

int main(void) {

	/* Initialize LED */
	gpio_led_init();
	/* Initialize user button */
	gpio_button_init();
	/* Initialize GPIO for I2C2 */
	gpio_i2c2_init_master();
	/* Initialize I2C2 */
	i2c2_init();
	/* Initialize EXTI */
	exti_init();

	/* Main loop */
    while(1) {
    	__WFI();
    }

    return 0;
}

