/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f070xb.h"
#include "uart.h"

int main(void) {

	/* Initialize UART1 and UART2 */
	uart1_init();
	uart2_init();
	/* Flag to indicate is received is finsihed */
	uint8_t isReceived = 0;

	/* Main loop */
    while(1) {
    	/* Initialize buffer to receive message */
    	static char receive_bit[CHAR_SIZE] = "\0\0";
    	static char receive_msg[MAX_SIZE] = "\0";

    	/* First receive, then transmit */
    	isReceived = receive(receive_bit, receive_msg);
    	if(isReceived) {
    		transmit();
    		/* Reset flag to be able to receive again */
    		isReceived = 0;
    	}
    }

    return 0;
}
