/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f070xb.h"
#include "dma.h"
#include "uart.h"
#include <string.h>

#define COSMIN_STRING	"Cosmin: "
uint16_t sent_bit = 65535;

int main(void) {

	static char sent_msg[MAX_SIZE] = "\0";
	static uint8_t len = 0;
	char output_sent_msg[MAX_SIZE + strlen(COSMIN_STRING)];
	char output_sent_msg_final[MAX_SIZE + strlen(COSMIN_STRING)];

	uart2_init();
	uart1_init();
	dma2_init();
	dma4_init();

	/* Main loop */
    while(1) {

    	/* Build message */
    	if (sent_bit != 65535) {
        	build_message(sent_msg, sent_bit, &len);
        	sent_bit = -1;
    	}
    	/* If \r is typed then send message */
    	if(sent_bit == '\r') {
    		strcat(output_sent_msg, COSMIN_STRING);
    		strcat(output_sent_msg, sent_msg);
    		strcat(output_sent_msg, "\r\n");
    		memcpy(output_sent_msg_final, output_sent_msg, sizeof(char) * (MAX_SIZE + strlen(COSMIN_STRING)));
    		dma2_write((uint32_t)output_sent_msg_final, strlen(output_sent_msg_final));
    		dma4_write((uint32_t)output_sent_msg_final, strlen(output_sent_msg_final));
    		memset(sent_msg, 0, (strlen(sent_msg) * sizeof(char)));
    		memset(output_sent_msg, 0, (strlen(output_sent_msg) * sizeof(char)));
    		len = 0;
    		sent_bit = 0;
    	}
    	/* At the same time, listen to message and interrupt if needed */
    }

    return 0;
}

